package metrics

import (
	"github.com/HelixDevelopment/HelixLLM/internal/shared/i18n"
)

// Package-level i18n seam for the metrics package.
//
// Per CONST-046, every user-facing string in this package — the
// Prometheus collector `Help` texts surfaced in Grafana panels,
// `/metrics` scrape output, alerting-rule editors, and Prometheus's
// own expression browser — MUST resolve through a Translator rather
// than living as a hardcoded English literal.
//
// Prometheus collectors are constructed in package-level `var`
// initialisers, before any consuming project has had the chance to
// wire a non-English Translator. The minimal honest seam for that
// constraint is a package-level Translator pre-loaded with the
// bundled English fallbacks: `helpText` resolves at var-init time and
// the no-wiring path still localises to English. Consuming projects
// that serve a non-English locale call SetTranslator + SetLang BEFORE
// importing this package's collectors (e.g. in an init ordering layer)
// or rebuild the descriptors after wiring; tests inject a fake.
//
// Decoupling per CONST-051(B): the seam binds only to HelixLLM's own
// shared/i18n package — no consumer-project type is referenced, so
// the metrics package remains reusable as a standalone unit.

// i18n message keys for the metrics package.
const (
	keyHelpModelInferenceTotal    = "metric_help_model_inference_total"
	keyHelpModelInferenceDuration = "metric_help_model_inference_duration"
	keyHelpModelTokensGenerated   = "metric_help_model_tokens_generated"
	keyHelpModelTokensPerSecond   = "metric_help_model_tokens_per_second"
	keyHelpRAGSearchDuration      = "metric_help_rag_search_duration"
	keyHelpRAGDocumentsIndexed    = "metric_help_rag_documents_indexed"
	keyHelpToolExecutionTotal     = "metric_help_tool_execution_total"
	keyHelpToolExecutionDuration  = "metric_help_tool_execution_duration"
	keyHelpAPIRequestsTotal       = "metric_help_api_requests_total"
	keyHelpAPIRequestDuration     = "metric_help_api_request_duration"
	keyHelpActiveConnections      = "metric_help_active_connections"
	keyHelpVRAMUsageBytes         = "metric_help_vram_usage_bytes"
	keyHelpRAMUsageBytes          = "metric_help_ram_usage_bytes"
)

// englishFallbacks is the bundled English text for every metrics-package
// key. It is loaded into the default Translator and also used by the
// last-resort renderFallback path so users never see a raw key.
var englishFallbacks = map[string]string{
	keyHelpModelInferenceTotal:    "Total number of model inferences.",
	keyHelpModelInferenceDuration: "Inference latency distribution in seconds.",
	keyHelpModelTokensGenerated:   "Total tokens generated by each model.",
	keyHelpModelTokensPerSecond:   "Current token generation rate (tokens/sec).",
	keyHelpRAGSearchDuration:      "RAG search latency distribution in seconds.",
	keyHelpRAGDocumentsIndexed:    "Total documents currently indexed in the RAG store.",
	keyHelpToolExecutionTotal:     "Total tool executions by tool name and status.",
	keyHelpToolExecutionDuration:  "Tool execution latency distribution in seconds.",
	keyHelpAPIRequestsTotal:       "Total API requests by endpoint, method, and HTTP status.",
	keyHelpAPIRequestDuration:     "API request latency distribution in seconds.",
	keyHelpActiveConnections:      "Number of currently active HTTP connections.",
	keyHelpVRAMUsageBytes:         "Current GPU VRAM usage in bytes.",
	keyHelpRAMUsageBytes:          "Current system RAM usage in bytes.",
}

// pkgTranslator is the package-level Translator used to resolve metric
// `Help` strings. Production wires a real Translator at init time via
// SetTranslator; tests inject a fake. The default is an English-only
// Translator pre-loaded with the bundled fallbacks so the no-wiring
// path still localises to English.
var pkgTranslator i18n.TranslatorAPI = newDefaultTranslator()

// pkgLang is the language tag passed to the package-level Translator.
// Consuming projects override it via SetLang when serving a non-English
// locale; the default is English.
var pkgLang = "en"

// newDefaultTranslator builds an English-only Translator pre-loaded
// with this package's bundled fallback strings.
func newDefaultTranslator() i18n.TranslatorAPI {
	tr := i18n.New("en")
	tr.LoadMessages("en", englishFallbacks)
	return tr
}

// SetTranslator wires a package-level Translator for the metrics
// package. Consuming projects call this at init time; tests use it to
// inject a fake. A nil argument resets to the English-only default.
func SetTranslator(tr i18n.TranslatorAPI) {
	if tr == nil {
		pkgTranslator = newDefaultTranslator()
		return
	}
	pkgTranslator = tr
}

// SetLang sets the language tag used when resolving metrics-package
// strings. An empty argument resets to English.
func SetLang(lang string) {
	if lang == "" {
		pkgLang = "en"
		return
	}
	pkgLang = lang
}

// helpText resolves a metrics-package i18n key to its locale-appropriate
// text. On a translator miss (key absent in every loaded language) the
// upstream Translator returns the key verbatim; helpText then substitutes
// the bundled English fallback so the user never sees a raw key.
func helpText(key string) string {
	got := pkgTranslator.T(pkgLang, key)
	if got == key {
		if msg, ok := englishFallbacks[key]; ok {
			return msg
		}
		return key
	}
	return got
}
