sonar.projectKey=helixllm
sonar.projectName=HelixLLM
sonar.projectVersion=1.0

sonar.sources=internal/,pkg/,cmd/
sonar.tests=internal/,tests/
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage-unit.out
sonar.go.tests.reportPaths=test-report.json

sonar.exclusions=submodules/**,vendor/**,bin/**,certs/**

sonar.qualitygate.wait=true
